import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
import LoginModal from "../components/LoginModal/LoginModal";
import RegisterModal from "../components/RegisterModal/RegisterModal";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let [isOpenLogin, setIsOpenLogin] = useState(false);
  let [isOpenRegister, setIsOpenRegister] = useState(false);
  return (
    <>
      <Head>
        <title>Firebase Authentication with Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        setIsOpenLogin={setIsOpenLogin}
        setIsOpenRegister={setIsOpenRegister}
      />
      <Hero
        setIsOpenLogin={setIsOpenLogin}
        setIsOpenRegister={setIsOpenRegister}
      />
      <LoginModal isOpenLogin={isOpenLogin} setIsOpenLogin={setIsOpenLogin} />
      <RegisterModal
        isOpenRegister={isOpenRegister}
        setIsOpenRegister={setIsOpenRegister}
      />
    </>
  );
}
